image: ruby:2.3

variables:
  JEKYLL_ENV: production

build:
 script:
  - bundle install
 only:
  - gh_pages
 

deploy:
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - gh_pages
